### ISSUE TITLE
Las constantes que has declarado aquí no son necesarias

### ISSUE THREAD

**Issue by josejuansanchez** [jacobo87/IAW-Practica05#3]
https://github.com/jacobo87/IAW-Practica05/blob/abf8eebab8d8b5f3ff438cbfc9efbdb11f33dc42/000-default.conf#L2

**Comment by jacobo87** [comment]
Si, además me he dado cuenta que al no comentarlas me peto la máquina. Las puse pensando en alguna necesidad futura. ¿Por lo demás entiendo que no necesita más? ¿Hay alguna forma de saber si esta balanceando la carga?

**Comment by josejuansanchez** [comment]
Puedes editar el archivo `/var/www/html/index.php` que tienes en cada uno de los frontales (Servidores Apache), y ponerle un texto específico a cada uno. Por ejemplo, puedes poner las etiquetas html `<h1>Front-End 1</h1>`  en el 172.31.88.61 y `<h1>Front-End 2</h1>` en el 172.31.90.13. 

Cuando accedas a la aplicación a través de la IP del balanceador verás que en algunos casos la página principal te muestra el texto `Front-End 1` y en otras `Front-End 2`.
